package ws.codewash.java;

public enum CWKeyword {
    ABSTRACT, ASSERT, BREAK, CASE, CATCH, CHAR, CLASS, CONTINUE, DEFAULT, DO, ELSE, EXTENDS, FINAL, FINALLY,
    FOR, IF, IMPLEMENTS, IMPORT, INSTANCEOF, INTERFACE, NATIVE, NEW, PACKAGE, RETURN, STATIC,SUPER, SWITCH,
    SYNCHRONIZED, THIS, THROW, THROWS, TRANSIENT, TRY, VOID, VOLATILE, WHILE,;
}
